### ISSUE TITLE
Acesso ao shiny

### ISSUE THREAD

**Issue by dan-rochag** [msperlin/GetDFPData2#10]
Bom dia professor, poderia por gentileza informar se há um acesso correto ao link do shiny  (versão web do GetDFPData2)? Tento acessar pelo link do blog, porém aparece uma mensagem "Page not found". Link é esse: https://msperlin.com/shiny/GetDFPData

Obrigado desde já

**Comment by dan-rochag** [comment]
Além disso, tenho outra dúvida. Você teria disponível um material "walktrough" sobre o GetDFPData2, como o A_ccessing Financial Reports and Corporate Events with GetDFPData_ para o GetDFPData? Como não sou experiente com R, me ajudaria bastante um material semelhante para a versão atualizada do seu pacote.

Muito obrigado, e parabéns pelo trabalho

**Comment by msperlin** [comment]
Respondido por email.
