### ISSUE TITLE
Ticker das empresas - GetDFPData2

### ISSUE THREAD

**Issue by dan-rochag** [msperlin/GetDFPData2#11]
Marcelo, sabe se é possível obter o ticker das empresas através do  get_info_companies? Aparentemente o ticker das empresas não fica disponível na tabela gerada

Abraço

**Comment by msperlin** [comment]
Oi Dan,

No passado sim, a informação era obtida junto ao site da B3. Infelizmente o site era instaável e retirei essa funcionalidade.

Mas, dá uma olhada nesse site aqui https://www.dadosdemercado.com.br/bolsa/acoes

Abc,
