### ISSUE TITLE
Erro no get_dfp_data

### ISSUE THREAD

**Issue by camurca1** [msperlin/GetDFPData2#3]
Ao executar a função get_dfp_data obtenho o seguinte erro:

Error in read_xml.raw(raw, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  Failed to parse text

código executado:
l.dfp <- get_dfp_data(companies_cvm_codes = 20990,
                      use_memoise = FALSE,
                      clean_data = TRUE,
                      type_docs = c('BPA', 'BPP', 'DRE', 'DFC_MI'),
                      type_format = 'con',
                      first_year = 2015,
                      last_year = 2020)

**Comment by camurca1** [comment]
Acabei de verificar que o portal de dados da CVM que o pacote se conecta está fora do ar.

**Comment by msperlin** [comment]
Poisé, também notei. Vamos esperar para ver o que acontece.

**Comment by camurca1** [comment]
Já está normalizado novamente!

Obrigado pelo pacote.
