### ISSUE TITLE
get_info_companies() not returning companies tickers

### ISSUE THREAD

**Issue by Shortiiiiie** [msperlin/GetDFPData2#4]
@msperlin Hi Professor,
Thank you so much for this package, its amazing. 

Yet, I'm not being able to retrieve a list of tickers of Brazilian companies from the DF 'get_info_companies()'. 
The list downloaded from cvm does not have a column covering the tickers itself. 

Can you please help me?

**Comment by msperlin-finor** [comment]
Hi there,

Unfortunately, as far as I know, ticker information is not available in any public sources besides b3 website. And I can't scrape their site due to their policies. If you've found a new public source, please let me know.

**Comment by msperlin** [comment]
Hi there,

Unfortunately, as far as I know, ticker information is not available in any public sources besides b3 website. And I can't scrape their site due to their policies. If you've found a new public source, please let me know.

**Comment by kafran** [comment]
### For future reference:

* B3 provides a sector classification list with the code for the traded companies. However, this code is not the traded ticker, but it helps:
  * https://www.b3.com.br/data/files/57/E6/AA/A1/68C7781064456178AC094EA8/ClassifSetorial.zip
* On the CVM's FCA, available at https://dados.cvm.gov.br/dataset/cia_aberta-doc-fca, the file `fca_cia_aberta_valor_mobiliario` includes the traded ticker. However, this source may not always be reliable. For instance, for the BPAC11 company (and a few others), the ticker is listed as '000000'  or unknown. I didn't investigate thoroughly, but it appears this has been the case for several years (Dados Cadastrais > Valores Mobiliários):
  * 2022: https://www.rad.cvm.gov.br/ENET/frmGerenciaPaginaFRE.aspx?NumeroSequencialDocumento=118534&CodigoTipoInstituicao=1
  * 2020: https://www.rad.cvm.gov.br/ENET/frmGerenciaPaginaFRE.aspx?NumeroSequencialDocumento=102871&CodigoTipoInstituicao=1

For sure this is an information that will need some curation.

**Comment by msperlin** [comment]
Thanks @kafran. I'll have a look and check if I can incorporate this information in the code.

**Comment by kafran** [comment]
> Thanks @kafran. I'll have a look and check if I can incorporate this information in the code.

If you have any other idea post it here as I am trying to develop an ETL workflow myself =)

**Comment by msperlin** [comment]
This seems to be the best way forward:

https://dados.cvm.gov.br/dataset/cia_aberta-doc-fca

I worked with these CVM files in the past and it is of great quality. I already know how to parse it. This week or next I'll try to implement it.

**Comment by kafran** [comment]
> This seems to be the best way forward:
> 
> https://dados.cvm.gov.br/dataset/cia_aberta-doc-fca
> 
> I worked with these CVM files in the past and it is of great quality. I already know how to parse it. This week or next I'll try to implement it.

I'll be using this datasets then. Do you know if they are cumulative? Can I rely solely on the most recent one from 2023? It appears that the key for this corpus is the Doc_ID, but I'm concerned about whether a company that hasn't submitted any changes in 2023 will still appear in the most recent corpus. This is vital for us to establish relationships for all companies with the CD_CVM.

**Comment by msperlin** [comment]
Yes, given the volume of data, I suspect it is cumulative. You'll probably be fine by using the most recent one.

**Comment by msperlin** [comment]
New function GetDFPData2::get_tickers() is now available. Let me know if it is working well (passed all my tests).
