### ISSUE TITLE
Erro no get_info_company

### ISSUE THREAD

**Issue by rafaellabbarreto** [msperlin/GetDFPData2#5]
Oi Professor! 
Tentei rodar os seguintes comandos no R:

df_info <- get_info_companies()
df_info <- get_info_companies(tempdir())

Ambos com o erro: 

_Fetching info on B3 companies
	Dowloading file from CVM
	File not found, downloading it..
sh: wget: command not found
Error in utils::download.file(url = dl_link, destfile = dest_file, method = "wget",  : 
  'wget' call had nonzero exit status
In addition: Warning message:
In system(paste("wget", paste(extra, collapse = " "), shQuote(url),  :
  error in running command
Error in if (file.size(dest_file) < 10) { : 
  missing value where TRUE/FALSE needed_

**Comment by msperlin** [comment]
Oi RAfella, 

Estás no Mac ou windows? 

Acredito que deves instalar o wget antes de rodar. Podes confirmar se isso resolve?

**Comment by rafaellabbarreto** [comment]
Não deu certo... 

Estou no Mac.

**Comment by rafaellabbarreto** [comment]
Professor, deu certo agora! instalei o wget e reiniciei, aí sim. Obrigada

**Comment by msperlin-finor** [comment]
Ok ótimo.
